#!/bin/sh
#
# Start watchdog
#

case "$1" in
 start)
	for dev in /dev/watchdog?*; do
		if [ -c $dev ]; then
			echo "Starting ${dev}..."
			watchdog -t PERIOD $dev
		fi
	done
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
